"""Adiciona campos em RetroativoArquivo

Revision ID: 15dd2404ba2d
Revises: c948af16672a
Create Date: 2025-07-04 15:13:16.172770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dd2404ba2d'
down_revision = 'c948af16672a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retroativos_calculados')
    op.drop_table('retroativos_arquivos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retroativos_arquivos',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nome_arquivo', sa.TEXT(), nullable=False),
    sa.Column('data_processamento', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_arquivo')
    )
    op.create_table('retroativos_calculados',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('artista', sa.TEXT(), nullable=False),
    sa.Column('ano', sa.INTEGER(), nullable=False),
    sa.Column('lucro_liquido', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
