"""adiciona TituloPeriodoValor

Revision ID: 48e8faba1fc9
Revises: 62cc78324810
Create Date: 2025-07-24 09:34:54.877772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e8faba1fc9'
down_revision = '62cc78324810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulo_periodo_valor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artista', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('origem_planilha', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titulo_periodo_valor')
    # ### end Alembic commands ###
