"""Adiciona tabela retroativos_titulos

Revision ID: 62cc78324810
Revises: 15dd2404ba2d
Create Date: 2025-07-08 14:04:15.649611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cc78324810'
down_revision = '15dd2404ba2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retroativos_titulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artista_nome', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artista_nome', 'titulo', name='uix_artista_titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retroativos_titulos')
    # ### end Alembic commands ###
