"""Add artista_nome to pagamento_realizado

Revision ID: c948af16672a
Revises: f048dd8bcad0
Create Date: 2025-06-20 11:48:02.233852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c948af16672a'
down_revision = 'f048dd8bcad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento_realizado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artista_nome', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento_realizado', schema=None) as batch_op:
        batch_op.drop_column('artista_nome')

    # ### end Alembic commands ###
