"""Adiciona campo vencimento em PagamentoRealizado

Revision ID: d79f2c2fd480
Revises: 
Create Date: 2025-06-18 14:27:04.722812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79f2c2fd480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento_realizado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vencimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento_realizado', schema=None) as batch_op:
        batch_op.drop_column('vencimento')

    # ### end Alembic commands ###
