"""Adiciona campo calculo_id em PagamentoRealizado

Revision ID: f048dd8bcad0
Revises: d79f2c2fd480
Create Date: 2025-06-18 15:29:56.852001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f048dd8bcad0'
down_revision = 'd79f2c2fd480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento_realizado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculo_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento_realizado', schema=None) as batch_op:
        batch_op.drop_column('calculo_id')

    # ### end Alembic commands ###
